apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy
  namespace: cafe
spec:
  waf:
    enable: true
    apPolicy: "default/dataguard-alarm"
    securityLog:
      enable: true
      apLogConf: "default/logconf"
      logDest: "syslog:server=10.217.5.192:514"
