apiVersion: k8s.nginx.org/v1alpha1
kind: NginxIngressController
metadata:
  name: my-nginx-ingress-controller
  namespace: nginx-ingress
spec:
  logLevel: 3
  wildcardTLS: ''
  enableCRDs: true
  ingressClass: nginx
  enableLeaderElection: false
  enableLatencyMetrics: false
  nginxStatus:
    allowCidrs: 127.0.0.1
    enable: true
    port: 9090
  watchNamespace: ''
  nginxReloadTimeout: 0
  healthStatus:
    enable: true
    uri: ''
  appProtect:
    enable: false
  serviceType: NodePort
  defaultSecret: ''
  globalConfiguration: ''
  nginxPlus: true
  enablePreviewPolicies: false
  service: null
  useIngressClassOnly: true
  enableSnippets: false
  nginxDebug: false
  type: deployment
  image:
    pullPolicy: Always
    repository: >-
      image-registry.openshift-image-registry.svc:5000/nginx-ingress/openshift-image-plus
    tag: 1.11.1
  replicas: null
  enableTLSPassthrough: true
status:
  deployed: true
